storage.body.size=50
storage.motor.size=50
storage.accessory.size=50
storage.car.size=50

suppliers.accessory.count=3
workers.count=5
dealers.count=3

delay.body=1000
delay.motor=1000
delay.accessory=1000
delay.dealer=1000

log.sale=true