storage.body.size=30
storage.motor.size=30
storage.accessory.size=100
storage.car.size=10

suppliers.accessory.count=3
workers.count=5
dealers.count=3

delay.body=1000
delay.motor=1000
delay.accessory=1000
delay.dealer=1000

log.sale=true