PUSH=ru.nsu.ccfit.veronika.calculator.commands.PushCommand
POP=ru.nsu.ccfit.veronika.calculator.commands.PopCommand
+=ru.nsu.ccfit.veronika.calculator.commands.AddCommand
-=ru.nsu.ccfit.veronika.calculator.commands.SubtractCommand
*=ru.nsu.ccfit.veronika.calculator.commands.MultiplyCommand
/=ru.nsu.ccfit.veronika.calculator.commands.DivideCommand
SQRT=ru.nsu.ccfit.veronika.calculator.commands.SqrtCommand
PRINT=ru.nsu.ccfit.veronika.calculator.commands.PrintCommand
DEFINE=ru.nsu.ccfit.veronika.calculator.commands.DefineCommand
EXIT=ru.nsu.ccfit.veronika.calculator.commands.ExitCommand
POW=ru.nsu.ccfit.veronika.calculator.commands.PowCommand
SIN=ru.nsu.ccfit.veronika.calculator.commands.SinCommand
COS=ru.nsu.ccfit.veronika.calculator.commands.CosCommand